#include <iostream>
using namespace std;

#include "Musician.h"

Musician::Musician() ...

Musician::Musician(std::string instrument, int experience) ...

string Musician::get_instrument()...

int Musician::get_experience() ...
